### ISSUE TITLE
wikibase with graph 3.2 data has mixed content?

### ISSUE THREAD

**Issue by NuriaQueralt** [SuLab/Krusty#10]
how to delete the current data?

* __option1__: [wikibase-docker](https://github.com/wmde/wikibase-docker/blob/master/README-compose.md)

```docker-compose down --volumes```

* __option2__: [ docker](http://docs.metasfresh.org/installation_collection/EN/How_do_I_reset_database_using_docker.html)

```
docker-compose stop
docker rm <name of your db container>
rm -r volumes/db
docker-compose up -d
```

**Comment by andrewsu** [comment]
I would ask at https://lists.wikimedia.org/mailman/listinfo/wikibaseug

**Comment by stuppie** [comment]
You want to wipe all data and start over? 

`docker-compose down --volumes`

will do that

**Comment by NuriaQueralt** [comment]
Thanks guys!

> I would ask at https://lists.wikimedia.org/mailman/listinfo/wikibaseug

I did it, but waiting for my subscription request to be accepted.. 

In the meanwhile, i also asked here: https://www.mediawiki.org/wiki/Talk:Wikibase/Installation/Advanced_configuration

**Comment by NuriaQueralt** [comment]
it worked, **run**:

```
$ docker-compose down --volumes
# service docker restart
$ docker-compose up -d
```
